### PR TITLE
Remove internal DNS entries of backends

### PR DESCRIPTION
**Pull request by ulich**
to further reduce Cloudformation resources

### CODE REVIEW

**Comment by sevos** [comment]
`InternalDNS` class is unused now, right?

**Comment by sevos** [comment]
reviewed

**Comment by ulich** [comment]
The InternalDNS class is still used to create the `baustell.internal` and `#{name}.#{region}.baustelle.internal` zone. We still have some DNS entries in that zone for e.g. the bastion host. Or can we remove those too?

**Comment by sevos** [comment]
No, we should keep them. Thanks. Reviewed.

**Pull request merged**
